### PR TITLE
Remove jquery from dependencies in AMD

### PR DESCRIPTION
**Pull request by jeerbl**
Refering to #127.

---
This change is [Reviewable](https://reviewable.io/reviews/hubspot/odometer/128)

### CODE REVIEW

**Comment by outdooricon** [comment]
@zackbloom @marcneuwirth @adamschwartz can we please get this in and released. This blocks odometer from being able to be used in more modern tools like webpack, when we aren't using jquery (which is quickly becoming common). I really need this so I can use this in our react app. Thank you very much!

**Comment by jeerbl** [comment]
Hello guys!

Any news on this? Can we merge this?

Thanks,
Jérôme

**Comment by alanrubin** [comment]
Please release that change ! I'm not using jQuery in my app and that is a blocker... Thanks for this great library !

**Comment by JetFault** [comment]
A temporary workaround for this is doing the same thing you would do for backbone without jQuery.

My webpack 2 config looks something like this:
```
module: {
    loaders: [
      {
        test: /(backbone|odometer)\.js$/,
        loader: 'imports-loader?define=>false'
      }
    ]
  },
  plugins: [
    new webpack.IgnorePlugin(/^jquery$/)
  ]
```

**Comment by jeerbl** [comment]
Sorry to ask again but, where are we on this? Is there anything holding up?

@zackbloom 

Thanks,
Jérôme

**Comment by zackbloom** [comment]
Sorry for the delay @jeerbl

**Comment by alanrubin** [comment]
Do you need to bump a new version to npm so we can get access to it? I'm having issues getting yarn to see the update.

**Comment by zackbloom** [comment]
Published as v0.4.8

**Pull request merged**
